_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app_localized:
    resource: "../src/Controller/"
    type:     annotation
    prefix:
        en: /en
        de: /de

app:
    resource: "../src/Controller/"
    type:     annotation

account-logout:
    path: '{_locale}/account/logout'

download_excel:
    path: '/download-excel/{filename}'
    controller: 'App\Controller\ContentController::downloadExcelAction'

# Add this new route to disable Symfony handling for /blog
blog_ignore:
    path: /blog
    controller: false

porter_ignore:
    path: /porter
    controller: false